version: '2.1'

services:
  team_run_backend:
    image: team_run_backend
    build: .
    environment:
      NODE_ENV: production
      MYSQL_URL: 10.165.18.63
    ports:
      - 3000:3000
    volumes:
      - image:/static/images
volumes:
  image: