version: '2.1'

services:
  team_run_backend:
    image: team_run_backend
    build: .
    environment:
      NODE_ENV: development
      MYSQL_URL: 10.165.18.63
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js
    volumes:
      - image:/static/images
volumes:
  image: